print("")
print("Zamarripa Castro Erick Fabián_3W_1220")
print("")

# Define el saludo para luego imprimir el texto declarado
def mostrar_saludo(nombre):
    print("Hola, " + nombre)
    print("")

# Solicita al usuario que ingrese su nombre
nombre_usuario = input("Por favor, ingresa tu nombre: ")

# Llamada a la función con el nombre proporcionado por el usuario
mostrar_saludo(nombre_usuario)

